/*
Copyright 2026 The provider-anthropic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	extractors "github.com/jonasz-lasut/provider-anthropic/internal/extractors"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Deployment.
func (mg *Deployment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AgentID),
		Extract:      extractors.ComputedFieldExtractor("id"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AgentIDRef,
		Selector:     mg.Spec.ForProvider.AgentIDSelector,
		To: reference.To{
			List:    &AgentList{},
			Managed: &Agent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AgentID")
	}
	mg.Spec.ForProvider.AgentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AgentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnvironmentID),
		Extract:      extractors.ComputedFieldExtractor("id"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.EnvironmentIDRef,
		Selector:     mg.Spec.ForProvider.EnvironmentIDSelector,
		To: reference.To{
			List:    &EnvironmentList{},
			Managed: &Environment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnvironmentID")
	}
	mg.Spec.ForProvider.EnvironmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnvironmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Resources); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Resources[i3].MemoryStoreID),
			Extract:      extractors.ComputedFieldExtractor("id"),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Resources[i3].MemoryStoreIDRef,
			Selector:     mg.Spec.ForProvider.Resources[i3].MemoryStoreIDSelector,
			To: reference.To{
				List:    &MemoryStoreList{},
				Managed: &MemoryStore{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Resources[i3].MemoryStoreID")
		}
		mg.Spec.ForProvider.Resources[i3].MemoryStoreID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Resources[i3].MemoryStoreIDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.VaultIDs,
		Extract:       extractors.ComputedFieldExtractor("id"),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.VaultIDsRefs,
		Selector:      mg.Spec.ForProvider.VaultIDsSelector,
		To: reference.To{
			List:    &VaultList{},
			Managed: &Vault{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VaultIDs")
	}
	mg.Spec.ForProvider.VaultIDs = mrsp.ResolvedValues
	mg.Spec.ForProvider.VaultIDsRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this MemoryStoreMemory.
func (mg *MemoryStoreMemory) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MemoryStoreID),
		Extract:      extractors.ComputedFieldExtractor("id"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MemoryStoreIDRef,
		Selector:     mg.Spec.ForProvider.MemoryStoreIDSelector,
		To: reference.To{
			List:    &MemoryStoreList{},
			Managed: &MemoryStore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MemoryStoreID")
	}
	mg.Spec.ForProvider.MemoryStoreID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MemoryStoreIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Session.
func (mg *Session) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AgentID),
		Extract:      extractors.ComputedFieldExtractor("id"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AgentIDRef,
		Selector:     mg.Spec.ForProvider.AgentIDSelector,
		To: reference.To{
			List:    &AgentList{},
			Managed: &Agent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AgentID")
	}
	mg.Spec.ForProvider.AgentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AgentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnvironmentID),
		Extract:      extractors.ComputedFieldExtractor("id"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.EnvironmentIDRef,
		Selector:     mg.Spec.ForProvider.EnvironmentIDSelector,
		To: reference.To{
			List:    &EnvironmentList{},
			Managed: &Environment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnvironmentID")
	}
	mg.Spec.ForProvider.EnvironmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnvironmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Resources); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Resources[i3].MemoryStoreID),
			Extract:      extractors.ComputedFieldExtractor("id"),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Resources[i3].MemoryStoreIDRef,
			Selector:     mg.Spec.ForProvider.Resources[i3].MemoryStoreIDSelector,
			To: reference.To{
				List:    &MemoryStoreList{},
				Managed: &MemoryStore{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Resources[i3].MemoryStoreID")
		}
		mg.Spec.ForProvider.Resources[i3].MemoryStoreID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Resources[i3].MemoryStoreIDRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: mg.Spec.ForProvider.VaultIDs,
		Extract:       extractors.ComputedFieldExtractor("id"),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.VaultIDsRefs,
		Selector:      mg.Spec.ForProvider.VaultIDsSelector,
		To: reference.To{
			List:    &VaultList{},
			Managed: &Vault{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VaultIDs")
	}
	mg.Spec.ForProvider.VaultIDs = mrsp.ResolvedValues
	mg.Spec.ForProvider.VaultIDsRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this VaultCredential.
func (mg *VaultCredential) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VaultID),
		Extract:      extractors.ComputedFieldExtractor("id"),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VaultIDRef,
		Selector:     mg.Spec.ForProvider.VaultIDSelector,
		To: reference.To{
			List:    &VaultList{},
			Managed: &Vault{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VaultID")
	}
	mg.Spec.ForProvider.VaultID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VaultIDRef = rsp.ResolvedReference

	return nil
}
