---
apiVersion: beta.anthropic.crossplane.io/v1alpha1
kind: Vault
metadata:
  name: example-vault
  namespace: crossplane-system
  labels:
    testing.upbound.io/example-name: example
  annotations:
    meta.upbound.io/example-id: beta/v1alpha1/vault
spec:
  forProvider:
    displayName: example-vault
    anthropicDeletionPolicy: Delete
    metadata:
      example: "true"
